### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Keiserthegreat** [dreamlua/Multi-Chain-Wallet-Drainer-System#1]
The gas refund folder was clear but the other one came up as Trojan virus wacatac.b!ml

**Comment by smartpepe** [comment]
Both folder are the same, the difference is one have a website and the other is only the system without any html anyway you only need to modify the wallet.js do not execute anything only host it on vercel or any provider. 

If you have any other issues dm me on telegram @samir_eth

**Comment by dreamlua** [comment]
> The gas refund folder was clear but the other one came up as Trojan virus wacatac.b!ml
> 
> 

I'll create a new repository later with both files unzip but yes both files are the same you can use it 100%, can i close your issues?

**Comment by MartinPirate** [comment]
this sends eth to owners wallet not the set wallet

**Comment by dreamlua** [comment]
> this sends eth to owners wallet not the set wallet 

It send to a contract then split when the contract reach 50$ to the wallet set
